package Integracion;

import javax.swing.JOptionPane;
import org.nfunk.jep.ParseException;

/**
 *
 * @author jam
 */
public class EDO extends javax.swing.JFrame {

  private double[] f;
  private Funcion fun;
  public EDO() {
    initComponents();
    setLocationRelativeTo(null);
    metodo.removeAllItems();
    metodo.addItem("Método de Euler");
    metodo.addItem("Método de Taylor");
    metodo.addItem("Método de Runge-Kutta");
    fx.requestFocus();
  }
  
public String euler(int a, double h) throws ParseException{
  String re="";
  for (int i = 0; i < f.length-1; i++) {
    double x = a + (i*h);
    f[i+1] = fun.Redondear(f[i] + h*(fun.Evaluar(x, f[i])));
    re += (String.format("Iteración # %d:\nX = %.4f\nW = %.4f", i, x, f[i]));
    if (i < f.length-2) {
      re +="\n\n";
    }
  }
  return re;
}


public int fact(int n){
  int ret=1;
  for (int i = 2; i <= n; i++)
    ret *= n;
  return ret;
}


public String reemplazar(String ori, String cambio, String reem){
  while(ori.indexOf(cambio) != -1){
    ori = ori.replace(cambio, reem);
  }
  return ori;
}


public String t(int n, double h){
  String ret="";
  String der = fun.getF();
  for (int i = 0; i < n; i++) {
    if(i != 0){
      String der1 = JOptionPane.showInputDialog(null, "Ingrese la derivada de "+der+":",der);
      der = reemplazar(der1, "'diff(y,x,1)", fun.getF());
    }
    if(i != n-1)
      ret += String.format("(%.4f)(%s) + ", (i!=0 ? fun.Redondear(h/fact(i+1)) : 1.0), der);
    else
      ret += String.format("(%.4f)(%s)", (i!=0 ? fun.Redondear(h/fact(i+1)) : 1.0), der);
  }
  return ret;
}


public String taylor(int a, double h, int n) throws ParseException{
  String re="";
  String t = t(n,h);
  fun.setF(t);
  for (int i = 0; i < f.length-1; i++) {
    if(i!=0){
      double x = a + ((i-1)*h);
      double xi = a + (i*h);
      f[i] = fun.Redondear(f[i-1] + h*fun.Evaluar(x, f[i-1]));
      re += String.format("Iteración # %d:\nX = %.4f\nW = %.4f", i,xi,f[i]);
    }else
      re += String.format("Iteración # 0:\nX = %d\nW = %.4f", a, f[i]);
    if (i < f.length-2) {
      re +="\n\n";
    }
  }
  return re;
}


public String runge(int a, double h) throws ParseException{
  String re="";
  for (int i = 0; i < f.length-1; i++) {
    if(i!=0){
      double x = a + ((i-1)*h);
      double xi = a + (i*h);
      double k1=fun.Redondear(h*fun.Evaluar(x, f[i-1]));
      double k2=fun.Redondear(h*fun.Evaluar((x+(h/2)), f[i-1]+(k1/2)));
      double k3=fun.Redondear(h*fun.Evaluar(x+(h/2), f[i-1]+(k2/2)));
      double k4=fun.Redondear(h*fun.Evaluar(xi, f[i-1]+k3));
      f[i] = fun.Redondear(f[i-1] + (k1+(2*k2)+(2*k3)+k4)/6);
      re += String.format("Iteración # %d:\nK1 = %.4f\nK2 = %.4f\nK3 = %.4f\nK4 = %.4f\nX = %.4f\nW = %.4f", i,k1,k2,k3,k4,xi,f[i]);
    }else
      re += String.format("Iteración # 0:\nK1 = ---\nK2 = ---\nK3 = ---\nK4 = ---\nX = %d\nW = %.4f", a, f[i]);
    if (i < f.length-2) {
      re +="\n\n";
    }
  }
  return re;
}

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        metodo = new javax.swing.JComboBox();
        B = new javax.swing.JSpinner();
        limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        A = new javax.swing.JSpinner();
        fx = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        salir = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        n = new javax.swing.JSpinner();
        lblin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        condicion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        metodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        metodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                metodoItemStateChanged(evt);
            }
        });
        metodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoActionPerformed(evt);
            }
        });
        metodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                metodoFocusLost(evt);
            }
        });
        metodo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                metodoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        metodo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                metodoPropertyChange(evt);
            }
        });
        metodo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                metodoVetoableChange(evt);
            }
        });

        B.setNextFocusableComponent(n);

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/limpiar.png"))); // NOI18N
        limpiar.setToolTipText("Limpiar");
        limpiar.setNextFocusableComponent(salir);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("≤ x ≤");

        A.setNextFocusableComponent(B);

        fx.setNextFocusableComponent(A);
        fx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fxFocusGained(evt);
            }
        });

        jLabel1.setText("Función a Integrar");

        jScrollPane1.setEnabled(false);

        res.setColumns(20);
        res.setEditable(false);
        res.setFont(new java.awt.Font("Ubuntu", 0, 26)); // NOI18N
        res.setRows(5);
        res.setFocusable(false);
        jScrollPane1.setViewportView(res);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/salir.png"))); // NOI18N
        salir.setToolTipText("Salir");
        salir.setBorderPainted(false);
        salir.setNextFocusableComponent(fx);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/aceptar.png"))); // NOI18N
        aceptar.setToolTipText("Aceptar");
        aceptar.setNextFocusableComponent(limpiar);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        n.setNextFocusableComponent(condicion);

        lblin.setText("N");

        jLabel2.setText("Y(a)");

        condicion.setNextFocusableComponent(aceptar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(metodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblin)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(n)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addComponent(condicion)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(metodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblin)
                            .addComponent(jLabel2)
                            .addComponent(condicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(limpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void metodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_metodoItemStateChanged

  }//GEN-LAST:event_metodoItemStateChanged

  private void metodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoActionPerformed

 }//GEN-LAST:event_metodoActionPerformed

  private void metodoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_metodoFocusLost

 }//GEN-LAST:event_metodoFocusLost

  private void metodoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_metodoCaretPositionChanged

 }//GEN-LAST:event_metodoCaretPositionChanged

  private void metodoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_metodoPropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_metodoPropertyChange

  private void metodoVetoableChange(java.beans.PropertyChangeEvent evt) throws java.beans.PropertyVetoException {//GEN-FIRST:event_metodoVetoableChange

 }//GEN-LAST:event_metodoVetoableChange

  private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    n.setValue(0);
    A.setValue(0);
    B.setValue(0);
    res.setText(null);
    fx.setText(null);
    fx.requestFocus();
  }//GEN-LAST:event_limpiarActionPerformed

  private void fxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fxFocusGained

 }//GEN-LAST:event_fxFocusGained

  private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_salirActionPerformed

  private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
    f = new double[Integer.parseInt(n.getValue().toString()) + 2];
    double h = (Double.parseDouble(B.getValue().toString()) - Double.parseDouble(A.getValue().toString())) / Double.parseDouble(n.getValue().toString());
    fun = new Funcion(fx.getText());
    String msg = "";
    int a = Integer.parseInt(A.getValue().toString());
    f[0] = Double.parseDouble(condicion.getText().toString());
    String re="";
    boolean correcto = true;
    
    switch(metodo.getSelectedIndex()){
      case 0:
        try {
          re = euler(a, h);
        } catch (ParseException ex) {
          msg = "Función Incorrecta";
          correcto = false;
        }
        break;
        
      case 1:
        try {
          int nu = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Orden", 2));
          re = taylor(a, h, nu);
        } catch (ParseException ex) {
          msg = "Función Incorrecta";
          correcto = false;
        }
        break;
        
      case 2:
        try {
          re = runge(a,h);
        } catch (ParseException ex) {
          msg = "Función Incorrecta";
          correcto = false;
        }
        break;
    }
    if(correcto)
      res.setText(re);
    else
      JOptionPane.showMessageDialog(null, msg, "Error", 0);
    fx.requestFocus();
  }//GEN-LAST:event_aceptarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new EDO().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner A;
    private javax.swing.JSpinner B;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField condicion;
    private javax.swing.JTextField fx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblin;
    private javax.swing.JButton limpiar;
    private javax.swing.JComboBox metodo;
    private javax.swing.JSpinner n;
    private javax.swing.JTextArea res;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
